### ISSUE TITLE
this is the error i am getting

### ISSUE THREAD

**Issue by kaman1** [inspireui/listapp#1]
![screenshot_20180228-222745](https://user-images.githubusercontent.com/11543508/36827715-e08ec1ca-1cda-11e8-8568-e30db2dbec2d.png)

**Comment by kaman1** [comment]
I have installed listable. http://whereinpensacola.com but the app is still not working

**Comment by inspireui** [comment]
Hi @kaman1 could we know you email to send hotfix for this bug, thank you!

**Comment by kaman1** [comment]
Umkamanc@gmail.com

**Comment by inspireui** [comment]
Please help to download the latest version v1.1 to fixed this issues - thank you!

**Comment by kaman1** [comment]
I am still getting errors



On Mar 2, 2018 10:09 AM, "InspireUI" <notifications@github.com> wrote:

Please help to download the latest version v1.1 to fixed this issues -
thank you!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/inspireui/listapp/issues/1#issuecomment-369966462>, or mute
the thread

**Comment by inspireui** [comment]
Hi, i mean the latest v1.1.2 - could you help to download it again and have a check?
